name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  GIT_USER_NAME: e-mine software
  GIT_USER_EMAIL: contato@e-mine.com.br

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: git config --global user.name $GIT_USER_NAME
      - run: git config --global user.email $GIT_USER_EMAIL
      - run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > .npmrc
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npm run release -- --ci